In [1]:
# Import libraries
import pandas as pd

# Load dataset
df = pd.read_csv("iris.csv")

# Show first 5 rows
print("First 5 rows:")
display(df.head())

# Dataset info
print("\nDataset Info:")
print(df.info())

# Missing values check
print("\nMissing Values:")
print(df.isnull().sum())

# Handling missing values (example: fill with mean)
df.fillna(df.mean(numeric_only=True), inplace=True)

# Remove duplicate rows
df = df.drop_duplicates()

# Standardize column names (optional)
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Final cleaned dataset
print("\nCleaned Data Info:")
print(df.info())

# Save cleaned dataset
df.to_csv("iris_cleaned.csv", index=False)
print("\n✅ Data Cleaning & Preprocessing Completed. Saved as iris_cleaned.csv")

First 5 rows:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None

Missing Values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Cleaned Data Info:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 147 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  147 non-null    float64
 1   sepal_width   147 non-null    float64
 2   petal_length  147 non-null    float64
 3   petal_width   147 non-null    float64
 4   species       147 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.9+ KB
None

✅ Data Cleaning & Preprocessing Completed. Saved as iris_cleaned.csv